// 英文界面内容（天体描述 + 科教知识卡片）。中文数据散落在各 astro/scene 数据文件中，
// 此处按 id 集中提供英文版，在 LANG==='en' 时于显示点（targetInfo / factsFor）覆盖，
// 保持中文数据文件不变。缺失键回退中文。

/** 天体描述（信息面板 desc 行）英文版，按 id。 */
export const DESC_EN = {
  // ── 行星 / 矮行星 ──
  sun: 'A G2V main-sequence star holding 99.86% of the Solar System\'s mass. Surface ~5772 K; its core fuses hydrogen, releasing 3.8×10²⁶ watts every second.',
  mercury: 'The innermost planet, locked in a 3:2 spin–orbit resonance. Airless, with a 600 °C day–night swing and a heavily cratered surface.',
  venus: 'Earth\'s near-twin in size, but smothered by a CO₂ atmosphere 92× Earth\'s pressure and sulfuric-acid clouds. Surface 465 °C; it spins backwards, and a day lasts longer than its year.',
  earth: 'The only world known to harbor life. 71% of its surface is liquid water, with a nitrogen–oxygen atmosphere and a large moon that steadies its axis. Your home.',
  mars: 'The Red Planet. Home to the tallest volcano (Olympus Mons, 21.9 km) and longest canyon (Valles Marineris, 4000 km) in the Solar System. Thin CO₂ air; dust storms can engulf the globe.',
  jupiter: 'The largest planet — 2.5× the mass of all the others combined. The Great Red Spot is an anticyclone raging for centuries, ringed by a strong magnetic field and lethal radiation belts.',
  saturn: 'A gas giant with a magnificent icy ring system, and a density lower than water. The rings average just ~20 m thick yet span tens of thousands of km.',
  uranus: 'An ice giant tipped on its side (98° axial tilt). Methane absorbs red light, giving its cyan hue; its atmosphere is the coldest in the Solar System (−224 °C).',
  neptune: 'The most distant planet, discovered through mathematics. It has the fastest winds in the Solar System (2100 km/h); its deep blue comes from methane and an unknown absorber.',
  pluto: 'A Kuiper Belt dwarf planet, mutually tidally locked with Charon. New Horizons flew by in 2015 and revealed the nitrogen-ice heart, Sputnik Planitia.',
  // ── 卫星 ──
  moon: 'Earth\'s only natural satellite, tidally locked to always show the same face. The only world beyond Earth humans have walked on.',
  phobos: 'Mars\'s larger moon, potato-shaped (27×22×18 km) on a very low orbit (9376 km), spiraling inward by 1.8 m per century.',
  deimos: 'Mars\'s smaller, more distant moon — irregular, blanketed in fine dust.',
  io: 'The most volcanically active body in the Solar System; Jupiter\'s tidal heating coats it in sulfur volcanoes, giving it a pizza-like yellow-orange hue.',
  europa: 'Beneath its ice shell hides an ocean holding more liquid water than all of Earth\'s — a prime target in the search for extraterrestrial life.',
  ganymede: 'The largest moon in the Solar System, bigger than Mercury, and the only moon with its own magnetic field.',
  callisto: 'The most heavily cratered body in the Solar System; its ancient surface, layered with impact scars, is 4 billion years old.',
  mimas: 'Its enormous Herschel crater makes it look strikingly like the "Death Star".',
  enceladus: 'South-polar "tiger stripe" fractures jet ice plumes that feed Saturn\'s E ring; its subsurface ocean holds organic molecules. With an albedo near 1, it is the whitest body in the Solar System.',
  tethys: 'Made almost entirely of water ice, with a density of just 0.98 g/cm³.',
  dione: 'An icy moon crisscrossed by bright ice cliffs across its trailing hemisphere.',
  rhea: 'Saturn\'s second-largest moon — an ancient, heavily cratered iceball.',
  titan: 'The only moon with a thick atmosphere (1.5× Earth\'s pressure), with lakes and rivers of liquid methane beneath a global orange haze.',
  iapetus: 'The yin-yang moon: its leading hemisphere is coal-black, its trailing hemisphere snow-white, with a mysterious ridge running along its equator.',
  miranda: 'The most geologically chaotic moon, home to Verona Rupes — the tallest cliff in the Solar System (20 km).',
  ariel: 'Uranus\'s brightest moon, with young canyons and plains.',
  umbriel: 'Uranus\'s darkest large moon — ancient and enigmatic.',
  titania: 'Uranus\'s largest moon, scored by huge rift canyons.',
  oberon: 'Uranus\'s outermost large moon, with mysterious dark material on its crater floors.',
  triton: 'The only large moon in a retrograde orbit — a captured Kuiper Belt object. At −235 °C, its nitrogen geysers erupt 8 km high.',
  charon: 'The largest moon relative to its primary (half Pluto\'s radius); mutually tidally locked with Pluto, with a dark-red "Mordor" cap at its north pole.',
  // ── 彗星 ──
  halley: 'The most famous periodic comet, returning every 75–76 years. Last seen in 1986, next in 2061.',
  halebopp: 'The great comet of 1997, naked-eye visible for 18 months; orbital period ~2500 years.',
  cg67p: 'The "rubber duck" comet orbited and studied by the Rosetta spacecraft in 2014–2016.',
  encke: 'The comet with the shortest orbital period (3.3 years), parent body of the Taurid meteor shower.',
  // ── 探测器 ──
  voyager1: 'Launched 1977; crossed the heliopause into interstellar space in 2012 — the most distant human-made object.',
  voyager2: 'The only probe to have visited Uranus and Neptune; entered interstellar space in 2018.',
  // ── 日球层边界 ──
  termshock: 'The boundary where the solar wind abruptly drops from supersonic to subsonic (~90 AU). Voyager 1 crossed it in 2004.',
  heliopause: 'The boundary where solar-wind pressure balances the interstellar medium — the edge of the Sun\'s domain (~121 AU). Beyond it lies interstellar space.',
  // ── 区域 ──
  belts: 'The Solar System\'s main disk structures: the asteroid belt (2.1–3.4 AU) and the Kuiper Belt (30–50 AU).',
  oortcloud: 'The Solar System\'s outermost spherical comet cloud, ~2,000–100,000 AU from the Sun — the home of long-period comets.',
  // ── 海外天体（TNO）──
  eris: 'The largest known dwarf planet (~2326 km across), slightly bigger than Pluto. Its discovery directly triggered Pluto\'s reclassification. A high-albedo scattered-disk object coated in nitrogen ice and methane frost; orbital period ~559 years.',
  sedna: 'One of the reddest known bodies, rich in organic tholins. Orbital period ~11,400 years with a perihelion of 76 AU, far beyond the Kuiper Belt — an inner-Oort / extended-orbit (ETNO) object. Reaches perihelion around 2076.',
  makemake: 'One of the brightest Kuiper Belt objects, named after the creator god of Rapa Nui (Easter Island). Deep-red surface of methane and ethane ice, albedo ~77%, with one faint moon (MK2).',
  haumea: 'The fastest-spinning large body in the Solar System (rotation just 3.9 hours), flung into a football shape (1000×750×500 km). Crystalline water ice, a thin ring, and two moons (Hiʻiaka and Namaka). Named for the Hawaiian goddess of fertility.',
  quaoar: 'A classical cold Kuiper Belt object with methane, ethane and crystalline water ice. In 2023 it was found to host a dense ring beyond the Roche limit, challenging ring-formation theory. Named for the Tongva creator god.',
  gonggong: 'One of the reddest known bodies, rich in organics. A scattered-disk object (perihelion 33 AU, aphelion 101 AU) on a steeply inclined orbit (30°). Named after the Chinese water god who unleashed floods; it has a moon, Xiangliu.',
  orcus: 'A plutino in 3:2 resonance with Neptune, on a Pluto-like but anti-phased orbit. Ice-rich and high-albedo, with a large moon Vanth (~280 km) in mutual tidal lock.',
  varuna: 'A dimmer Kuiper Belt object; its 6.3-hour spin produces marked brightness variations. Named for the Hindu god of oceans and cosmic order.',
  ixion: 'A plutino in 3:2 resonance, reddish in color. Named for the Greek king condemned by Zeus to spin forever on a fiery wheel.',
  huya: 'A plutino in 3:2 resonance. Named for the rain god of the Venezuelan Wayuu people; it has a small moon in mutual tidal lock.',
  salacia: 'A cold classical Kuiper Belt object with an unusually high albedo (~12%) and a water-ice-rich surface. Has a moon, Actaea. Named for the Roman sea goddess, wife of Neptune.',
  ms4: 'A large unnamed Kuiper Belt object (~800 km across), nearly spherical. Not yet formally named; a possible dwarf-planet candidate.',
  chaos: 'A cold classical Kuiper Belt object, named for the primordial void at the origin of the world in Greek myth.',
  varda: 'A Kuiper Belt object with a relatively large moon, Ilmarë. Named for the Vala queen of the stars in Tolkien\'s legendarium.',
  typhon: 'A scattered-disk object with a perihelion of ~17 AU (inside Neptune\'s orbit) on a highly elliptical path. Named for the most fearsome monster of Greek myth; has a moon, Echidna.',
  tx300: 'A Kuiper Belt object with an extremely high albedo (88%) and a water-ice-rich surface, much like Enceladus. Occultations confirm a near-spherical shape.',
  ux25: 'A Kuiper Belt object with a moon. Its density of ~0.82 g/cm³ implies a water-ice-dominated, rock-poor interior — unusually low among known trans-Neptunian objects.',
  uk126: 'A scattered-disk object (perihelion ~37 AU, aphelion ~109 AU). Reddish, organic-rich surface, with one moon.',
  fy27: 'A scattered-disk object (perihelion ~30 AU, inclination 33°). Occultations show a high albedo and an estimated diameter of ~740 km — a possible dwarf-planet candidate.',
  ceto: 'A scattered-disk object (perihelion ~17 AU, aphelion ~187 AU, period ~1032 years). Has a moon, Phorcys. Named for the Greek sea goddess Ceto.',
  az84: 'A plutino in 3:2 resonance, close to a slightly oblate spheroid (axial ratio ~1:0.7:0.6). Precisely measured by occultations — one of the better-characterized Kuiper Belt objects.',
  gv9: 'A cold classical Kuiper Belt object on a near-circular orbit; thermal measurements estimate a diameter of ~530 km. Its 22° inclination places it in the hotter classical group.',
  rhadamanthus: 'A plutino in 3:2 resonance. Named for Rhadamanthus, the just judge of the underworld in Greek myth, a son of Zeus renowned for fairness.',
  qu182: 'A Kuiper Belt object of the intermediate-period group (~364 years). Thermal measurements estimate a diameter of ~416 km — a possible dwarf-planet candidate.',
  goblin: 'An extreme trans-Neptunian object (ETNO) with perihelion ~65 AU and aphelion beyond 2100 AU (period ~35,600 years). Discovered in 2015; its clustered orbit is among the hints for a possible Planet Nine.',
  vp113: 'An extended scattered-disk object with perihelion ~80 AU — at discovery the most distant perihelion of any known Solar System body (later surpassed by Sedna). Its clustered orbit is key evidence for the "Planet Nine" hypothesis. Nicknamed "Biden" (V and P resemble VP).',
  farout: 'At its 2018 discovery, the most distant known Solar System body (~124 AU), nicknamed "Farout". Estimated ~620 km across, with a pink surface suggesting ice; period ~5645 years.',
  farfarout: 'Confirmed in 2021 as a new record — the most distant known Solar System body at discovery (~132 AU). Nicknamed "FarFarOut". Perihelion ~50 AU, aphelion ~575 AU, period ~5515 years.',
};

/** 科教知识卡片英文版，按 id（与 eduFacts.js 的 FACTS 键一致）。 */
export const FACTS_EN = {
  sun: [
    'The Sun fuses ~600 million tonnes of hydrogen into helium every second; the 4 million tonnes of lost mass become light and heat via E=mc².',
    'Light takes tens of thousands of years to crawl from the Sun\'s core to its surface (absorbed and re-emitted endlessly), but only 8 min 20 s to reach Earth.',
    'Solar activity follows an ~11-year cycle; at its peak, sunspots, flares and coronal mass ejections surge and can disrupt Earth\'s power grids and satellites.',
  ],
  mercury: [
    'From Mercury the Sun looks only 2.4–3.2× larger than from Earth (1.1°–1.7° across, varying over its very elliptical orbit) — but 6–10× brighter, dazzlingly so. The Sun in space is far "smaller" than you\'d imagine.',
    'A "day" on Mercury (sunrise to sunrise) lasts 176 Earth days — twice its year (88 days)! This stems from its 3:2 spin–orbit resonance.',
    'Permanently shadowed polar craters on Mercury hold water ice — even though it is the planet closest to the Sun.',
    'The precession of Mercury\'s perihelion baffled astronomers for decades, until Einstein\'s general relativity explained it perfectly.',
  ],
  venus: [
    'Venus\'s surface pressure equals being 900 m underwater on Earth, and 465 °C is hot enough to melt lead — the textbook case of a runaway greenhouse.',
    'Venus spins backwards relative to other planets (the Sun rises in the west), and one rotation (243 days) takes longer than its year (225 days).',
    'About 50 km up, at the top of Venus\'s sulfuric-acid clouds, temperature and pressure resemble Earth\'s surface — once proposed as a "cloud colony" site.',
  ],
  earth: [
    'Earth is the only known planet with long-lived surface liquid water — the zone where it can exist is the "habitable zone" (Goldilocks Zone).',
    'Earth\'s magnetic field, generated by the convective dynamo of liquid iron in its outer core, deflects the solar wind and shields the atmosphere from being stripped away.',
    'Seen from the Moon, Earth\'s "phases" are exactly complementary to the Moon\'s: at new moon it is a "full Earth".',
    'Earth\'s rotation is slowing by ~1.8 milliseconds per century from lunar tidal friction — and the Moon drifts 3.8 cm farther away each year as a result.',
  ],
  moon: [
    'The Moon recedes from Earth by 3.8 cm per year — laser retroreflectors left by the Apollo missions still measure this precisely today.',
    'Tidal locking keeps the Moon\'s same face toward Earth, but thanks to libration we actually see 59% of its surface.',
    'The Moon likely formed 4.5 billion years ago in a giant impact between the primordial Earth and a Mars-sized body, "Theia".',
    'Try jumping right now — the Moon\'s gravity is only 1/6 of Earth\'s; Apollo astronauts said walking felt like a "slow-motion trampoline".',
  ],
  mars: [
    'Olympus Mons rises 21.9 km — 2.5× Everest — because Mars has no plate tectonics, so a volcano can keep growing over a hotspot.',
    'Mars once had oceans and rivers: Curiosity and Perseverance hunt for traces of ancient life in old riverbeds and lakebed sediments.',
    'Mars\'s atmosphere is 95% carbon dioxide at under 1% of Earth\'s pressure; surface liquid water would instantly boil or freeze.',
    'Sunsets on Mars are blue — dust scatters light in exactly the opposite way to Earth\'s atmosphere.',
  ],
  phobos: ['Phobos orbits below the synchronous altitude, and tidal forces are slowly dragging it toward Mars; in ~50 million years it will break into a ring or crash down.'],
  deimos: ['Deimos may be a captured asteroid, its surface buried under a thick layer of dust.'],
  jupiter: [
    'Jupiter\'s mass is 2.5× that of the other seven planets combined; its gravity acts like a "cosmic vacuum cleaner", shielding the inner Solar System from comet impacts.',
    'The Great Red Spot is an anticyclonic storm raging for at least 350 years — large enough to swallow 1–2 Earths, though it is slowly shrinking.',
    'Jupiter\'s radiation belts are deadly: a single day\'s dose at Europa\'s surface would kill a human.',
  ],
  io: ['Io has over 400 active volcanoes — the most volcanically active body in the Solar System, powered by Jupiter\'s relentless tidal kneading.'],
  europa: ['The ocean beneath Europa\'s ice shell holds about twice the water of all Earth\'s oceans combined. NASA\'s "Europa Clipper" is on its way to probe its habitability.'],
  ganymede: ['Ganymede is bigger than Mercury and the only moon with its own magnetic field, hiding a salty ocean beneath its ice shell.'],
  callisto: ['Callisto is the most heavily cratered body in the Solar System, geologically nearly dead for 4 billion years — a "living fossil" of the Solar System.'],
  saturn: [
    'Over 99% of Saturn\'s rings are water-ice particles (micrometres to metres); the pale gold-brown tint comes from trace silicates and organics mixed in.',
    'Saturn\'s rings span 280,000 km yet average only ~10–20 m thick — proportionally a hundred times thinner than a sheet of paper.',
    'Saturn is less dense than water (0.687 g/cm³) — in theory it would float in a large enough pool.',
    'Saturn\'s rings are "young" — perhaps only 10–100 million years old — and are raining down onto Saturn, possibly vanishing within 300 million years.',
  ],
  mimas: ['Mimas\'s Herschel crater is 139 km across — a third of its diameter; a slightly larger impact would have shattered it.'],
  enceladus: ['Cassini flew through Enceladus\'s icy plumes and sampled hydrogen molecules and organics — its subsurface ocean has the chemical energy life needs.'],
  titan: [
    'Titan is the only moon with a thick atmosphere (1.5× Earth\'s pressure), with methane rain, methane rivers and methane lakes on its surface.',
    'NASA\'s nuclear-powered "Dragonfly" rotorcraft will land on Titan in the 2030s to fly and survey its low-gravity, thick-atmosphere world.',
  ],
  iapetus: ['Iapetus is half coal-black, half snow-white, with a mysterious 13-km-high ridge along its equator — possibly the remains of an ancient fallen ring system.'],
  uranus: [
    'Uranus rotates on its side (98° axial tilt), probably from an ancient planet-scale collision; each of its seasons lasts 21 years.',
    'Uranus has the coldest planetary atmosphere in the Solar System (−224 °C), even though Neptune is farther from the Sun.',
  ],
  neptune: [
    'Neptune was the first planet "calculated" into existence — in 1846 Le Verrier predicted its position with pen and paper from anomalies in Uranus\'s orbit.',
    'Winds on Neptune reach 2100 km/h, the fastest in the Solar System — their energy source remains a mystery.',
  ],
  triton: ['Triton orbits backwards — a captured Kuiper Belt object; its nitrogen-ice geysers spray 8 km high.'],
  pluto: [
    'Pluto\'s heart-shaped Sputnik Planitia is a flowing glacier of nitrogen ice that resurfaces every few hundred thousand years.',
    'Pluto and Charon are mutually tidally locked — forever facing each other, like an eternal pair dancing.',
    'In 2006 the IAU redefined "planet", and Pluto was reclassified as a dwarf planet for not having "cleared its orbital neighborhood".',
  ],
  charon: ['Charon\'s radius is half of Pluto\'s, and their center of mass lies outside Pluto — making them more of a "double dwarf planet" system.'],
  halley: [
    'Halley was the first comet predicted to return (by Halley in 1705). Its tail debris feeds the annual Orionid meteor shower.',
    'During its 1986 return, ESA\'s Giotto probe flew through the coma and imaged the nucleus — a 15-km-long "dirty snowball".',
  ],
  halebopp: ['Comet Hale–Bopp was naked-eye visible for a record 18 consecutive months in 1997; its next return is ~2500 years away.'],
  cg67p: ['Rosetta orbited 67P in 2014 and dropped the Philae lander — humanity\'s first soft landing on a comet nucleus, finding glycine and other life-building molecules.'],
  encke: ['Comet Encke loops the Sun every 3.3 years, the shortest period of any comet; the Taurid meteor shower comes from the dust it sheds.'],
  voyager1: [
    'Voyager 1 carries the "Golden Record" with sounds of Earth and greetings in 55 languages — it will drift through interstellar space for billions of years.',
    'In 1990 Voyager 1 looked back from 6 billion km to capture the "Pale Blue Dot" — Carl Sagan: that is our only home.',
  ],
  voyager2: ['Voyager 2 used a once-in-176-years planetary alignment for its "Grand Tour" — the only probe to have visited all four outer planets.'],
  termshock: ['Here the solar wind abruptly drops from supersonic (~400 km/s) to subsonic — like the circular standing wave where a faucet\'s stream hits the sink.'],
  heliopause: ['The heliopause is where solar-wind pressure balances the interstellar medium. Crossing it, the Voyagers detected plasma density jump 40-fold — the moment they truly left the Sun\'s embrace.'],
  _generic: [
    'All the planets in the Solar System together hold just 0.14% of the Sun\'s mass.',
    'Shrink the Solar System to the size of a coin (Neptune\'s orbit) and the nearest star, Proxima Centauri, would be ~140 m away.',
    'All starlight you see is from the "past": Jupiter\'s light took tens of minutes, Proxima Centauri\'s took 4.2 years.',
    'The Solar System orbits the galactic center at 230 km/s, taking 230 million years per lap — last time it was here, the dinosaurs were just appearing.',
  ],
};
